# Generated by Django 5.1.3 on 2024-12-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone_parent',
            field=models.IntegerField(max_length=15),
        ),
    ]
